### ISSUE TITLE
Error for babel language option USenglish

### ISSUE THREAD

**Issue by yashcao** [klb2/review-response-template#1]
Package babel Error: You haven't defined the language 'USenglish' yet. \begin{document}

**Comment by klb2** [comment]
I am aware that this error for some/(older?) versions of babel. I changed the default language from `USenglish` to `american`. This should always work.
Alternatively, you can also use any other language that babel defines, e.g., `english`.

**Comment by yashcao** [comment]
> I am aware that this error for some/(older?) versions of babel. I changed the default language from `USenglish` to `american`. This should always work. Alternatively, you can also use any other language that babel defines, e.g., `english`.

Thanks a lot, I have updated the Texlive and it works! Thanks for the authors!
